#!/usr/bin/env bash

# Declare clang version and install if necessary
: ${CLANG_VERSION="3.8.0"}
: ${CLANG_VERSION_MAJOR_MINOR="$(echo ${CLANG_VERSION} | cut -d'.' -f1,2)"}

if [ -f "install-clang" ]; then
    ./install-clang "${CLANG_VERSION}"
fi

## Ensure requisite version of clang on PATH
: ${CLANG="clang-${CLANG_VERSION_MAJOR_MINOR}"}
: ${CLANGPP="clang++-${CLANG_VERSION_MAJOR_MINOR}"}

command -v "${CLANG}" > /dev/null || {
    echo "${CLANG} not found on PATH; aborting"
    exit 1
}

command -v "${CLANGPP}" > /dev/null || {
    echo "${CLANGPP} not found on PATH; aborting"
    exit 1
}

## R configure settings
: ${PREFIX="${HOME}/r/r-devel-sanitizers"}
: ${SANFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize=float-divide-by-zero"}
: ${ENABLE_R_FRAMEWORK="no"}
: ${R_NO_BASE_COMPILE="yes"}

## R compilation flags
## Note that compilation takes too long with optimization enabled.
: ${CC="${CLANG} -std=gnu99 ${SANFLAGS}"}
: ${CFLAGS="-g -Wall -pedantic"}
: ${CXX="${CLANGPP} ${SANFLAGS}"}
: ${CXXFLAGS="-g -Wall -pedantic"}
: ${F77="gfortran"}
: ${FC="gfortran"}

## Make sure that we use the clang++ compiler when building
## the R executable, so that sanitizer machinery gets compiled
## in. Note that we need to use clang++ to enable e.g. the 'vptr'
## sanitizer for C++ code. See:
##
##   https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Undefined-Behaviour-Sanitizer 
##
## for more information.
: ${LLVM_BIN_DIR="$(dirname `which ${CLANG} | xargs readlink`)"}
: ${MAIN_LD="${CLANGPP} -fsanitize=undefined -L\\\"${LLVM_BIN_DIR}/../lib/clang/${CLANG_VERSION}/lib/darwin\\\" -lclang_rt.asan_osx_dynamic"}

## Invoke install homebrew script with these variables
. install-r-homebrew || {
    echo "Failed to install R; aborting"
    exit 1
}

## Update Renviron so that we don't make use of '~/.R/Makevars'
cat << EOF >> "${PREFIX}/lib/R/etc/Renviron"
R_MAKEVARS_USER='~/.R/Makevars.san'
R_LIBS_USER='${PREFIX}/library'
EOF

## Ensure 'Makevars.san' exists (otherwise R configure can break)
mkdir -p "~/.R"
touch "~/.R/Makevars.san"

