#!/usr/bin/env sh

## Run an R command within LLDB, in batch mode.
: ${R_HOME:=/Library/Frameworks/R.framework/Resources}
: ${REXEC:=/Library/Frameworks/R.framework/Resources/bin/exec/R}

R_HOME=${R_HOME} lldb --batch --file "${REXEC}" -o "process launch -- -f $1"
