#!/usr/bin/env bash

Emacs () {
	"/Applications/Emacs.app/Contents/MacOS/Emacs" "$@" &
}

r-switch () {

	if test "$#" -ne 1
	then
		echo "Usage: r-switch [version]"
		return
	fi

	local VERSIONS_PATH
	VERSIONS_PATH=/Library/Frameworks/R.framework/Versions
	if [ ! -e "${VERSIONS_PATH}/$1" ]; then
		echo "R $1 is not installed in '${VERSIONS_PATH}'"
		return 1
	fi

	if [ -e "${VERSIONS_PATH}/Current" ]; then
		sudo unlink "${VERSIONS_PATH}/Current"
	fi

	sudo ln -fs "$1" "${VERSIONS_PATH}/Current"
	sudo ln -fs "/Library/Frameworks/R.framework/Resources/bin/R" "/usr/local/bin/R"

	local R_SESSION_INFO
	R_SESSION_INFO="$(/usr/local/bin/R --vanilla --slave -e "utils::sessionInfo()")"
	echo "${R_SESSION_INFO}" | head -n 3
}

rstudio-dev () {
	local OWD
	OWD="$(pwd)"
	cd ~/rstudio/src/xcode-build || return
	./desktop-mac/Debug/RStudio.app/Contents/MacOS/RStudio "$@" &
	cd "${OWD}" || return
}


