#!/usr/bin/env sh

## Run an R command within LLDB, in batch mode.
: ${R_HOME="`R RHOME | xargs greadlink -f`"}
: ${R_EXEC="${R_HOME}/bin/exec/R"}

R_HOME=${R_HOME} lldb --batch --file "${R_EXEC}" -o "process launch -- -f $1"
