#!/usr/bin/env bash

is-darwin () {
	test "$(uname)" = "Darwin"
}

is-linux () {
	test "$(uname)" = "Linux"
}

is-ubuntu () {
	[ "$(. /etc/os-release; echo "${ID}")" = "ubuntu" ]
}

is-redhat () {
	[ -f /etc/redhat-release ]
}

is-centos () {
	grep -siq "centos" /etc/redhat-release
}

is-fedora () {
	grep -siq "fedora" /etc/redhat-release
}

is-opensuse () {
	[ "$(. /etc/os-release; echo "${ID}")" = "opensuse" ]
}

if is-darwin; then
	for SCRIPT in ~/.login/bash/darwin/darwin-bash-*; do . "${SCRIPT}"; done
fi

if is-linux; then
	for SCRIPT in ~/.login/bash/linux/linux-bash-*; do . "${SCRIPT}"; done
fi

