#!/usr/bin/env bash

alias tc="vim ~/.tmux.conf"
alias v="vim"
alias vi="vim -u ~/.vim/startup/sensible.vim"

alias rgrep="grep -r"
alias untar="tar -xvf"

alias R="R_GC_MEM_GROW=3 R --min-vsize=2048M --min-nsize=20M --no-restore"

complete -F _todo t

