#!/usr/bin/env bash

is-darwin () {
	test "$(uname)" = "Darwin"
}

is-linux () {
	test "$(uname)" = "Linux"
}

is-ubuntu () {
	is-linux && test -n "$(lsb_release -i 2> /dev/null | grep "Ubuntu")"
}

is-centos () {
	is-linux && test -n "$(lsb_release -i 2> /dev/null | grep "CentOS")"
}

is-redhat () {
	is-linux && test -f /etc/redhat-release
}

if is-darwin; then
	for SCRIPT in ~/.login/bash/darwin/darwin-bash-*; do . "${SCRIPT}"; done
fi

if is-linux; then
	for SCRIPT in ~/.login/bash/linux/linux-bash-*; do . "${SCRIPT}"; done
fi

