#!/usr/bin/env bash

# TODO: detect appropriate version of lua?
: ${LUA="lua5.2"}
: ${PYTHON="python3.6"}

check () {
	if test $? -ne 0; then
		echo "$@"
		exit $?
	fi
}

## Install the various dependencies
sudo apt-get install -y -q \
	libncurses5-dev        \
	libgnome2-dev          \
	libgnomeui-dev         \
	libgtk2.0-dev          \
	libatk1.0-dev          \
	libbonoboui2-dev       \
	libcairo2-dev          \
	libx11-dev             \
	libxpm-dev             \
	libxt-dev              \
	${PYTHON}-dev          \
	ruby-dev               \
	mercurial              \
	ruby                   \
	${LUA}                 \
	lib${LUA}-dev


## clone from GitHub
if [ ! -d ~/.vim/sources ]; then
	echo "==> Cloning Vim ..."
	git clone https://github.com/vim/vim ~/.vim/sources
fi

# Check out relevant commit
cd ~/.vim/sources
if [ -z "$1" ]; then
	VIM_GIT_BRANCH="master"
else
	VIM_GIT_BRANCH="$1"
fi
git checkout "${VIM_GIT_BRANCH}"

echo "Configuring Vim..."
make distclean
make clean

./configure                      \
	--with-features=huge         \
	--enable-fail-if-missing     \
	--enable-multibyte           \
	--enable-largefile           \
	--enable-luainterp           \
	--enable-terminal            \
	--enable-rubyinterp          \
	--enable-python3interp       \
	--enable-cscope              \
	--with-lua                   \
	--with-x                     \
	--prefix=/usr/local

check "Configure FAILED!"

echo "Making Vim..."
make -j8
check "make FAILED!"

echo "Installing Vim..."
sudo make install
check "install FAILED!"

echo "Updating alternatives..."
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 1
sudo update-alternatives --set editor /usr/bin/vim

sudo update-alternatives --install /usr/bin/vi vi /usr/bin/vim 1
sudo update-alternatives --set vi /usr/bin/vim

echo "Done!"

